<?php

namespace Database\Seeders\Tenant;

use App\Models\Tenant\Especialidade;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EspecialidadeTableSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['name' => 'ACUPUNTURA'],
            ['name' => 'AGENTE COMUNITÁRIO DE SAÚDE'],
            ['name' => 'ALERGIA E IMUNOLOGIA'],
            ['name' => 'ANATOMOPATOLOGISTA'],
            ['name' => 'ANESTESIOLOGISTA'],
            ['name' => 'ANGIOLOGIA'],
            ['name' => 'ASSISTENTE SOCIAL'],
            ['name' => 'ATENDENTE DE CONSULTÓRIO DENTÁRIO'],
            ['name' => 'AUXILIAR DE ENFERMAGEM'],
            ['name' => 'AUXILIAR DE FARMÁCIA DE MANIPULAÇÃO'],
            ['name' => 'AUXILIAR DE LABORATÓRIO DE ANÁLISES CLÍNICAS'],
            ['name' => 'AUXILIAR DE RADIOLOGIA (REVELAÇÃO FOTOGRAFICA)'],
            ['name' => 'AUXILIAR EM SAÚDE BUCAL DA ESTRATÉGIA DE SAÚDE DA FAMÍLIA'],
            ['name' => 'AUXILIAR TÉCNICO EM PATOLOGIA CLÍNICA'],
            ['name' => 'BIOLOGO'],
            ['name' => 'BIOMÉDICO'],
            ['name' => 'CANCEROLOGISTA CIRURGICO (ONCOLOGISTA CIRURGICO)'],
            ['name' => 'CARDIOLOGIA'],
            ['name' => 'CARDIOPEDIATRIA'],
            ['name' => 'CIRURGIA CARDIOVASCULAR'],
            ['name' => 'CIRURGIA DA MÃO'],
            ['name' => 'CIRURGIA DE CABEÇA E PESCOÇO'],
            ['name' => 'CIRURGIA DO APARELHO DIGESTIVO'],
            ['name' => 'CIRURGIA GERAL'],
            ['name' => 'CIRURGIAO DENTISTA - CLINICO GERAL'],
            ['name' => 'CIRURGIAO DENTISTA - DENTISTICA'],
            ['name' => 'CIRURGIAO DENTISTA DE SAUDE COLETIVA'],
            ['name' => 'CIRURGIAO DENTISTA - ENDODONTISTA'],
            ['name' => 'CIRURGIAO DENTISTA - ESTRATEGIA SAUDE DA FAMILIA'],
            ['name' => 'CIRURGIÃO DENTISTA - IMPLANTODONTISTA'],
            ['name' => 'CIRURGIAO DENTISTA - ORTOPEDISTA E ORTODONTISTA'],
            ['name' => 'CIRURGIAO DENTISTA - PATOLOGISTA BUCAL'],
            ['name' => 'CIRURGIÃO DENTISTA - PERIODONTISTA'],
            ['name' => 'CIRURGIAO DENTISTA - RADIOLOGISTA'],
            ['name' => 'CIRURGIAO DENTISTA - TRAUMATOLOGISTA BUCOMAXILOFACIAL'],
            ['name' => 'CIRURGIA PEDIATRICA'],
            ['name' => 'CIRURGIA PLÁSTICA'],
            ['name' => 'CIRURGIA TORÁCICO'],
            ['name' => 'CIRURGIA VASCULAR'],
            ['name' => 'CLINICA MEDICA'],
            ['name' => 'CLINICO GERAL'],
            ['name' => 'CURSO DE DEPENDÊNCIA QUÍMICA'],
            ['name' => 'DERMATOLOGIA'],
            ['name' => 'DIRETOR DE SERVIÇOS DE SAÚDE'],
            ['name' => 'EDUCADOR FÍSICO'],
            ['name' => 'ENDOCRINOLOGIA E METABOLOGIA'],
            ['name' => 'ENDOCRINOLOGISTA PEDRIATRA'],
            ['name' => 'ENDOSCOPISTA'],
            ['name' => 'ENFERMEIRO'],
            ['name' => 'ESTETICISTA'],
            ['name' => 'FARMACEUTICO'],
            ['name' => 'FARMACEUTICO BIOQUIMICO'],
            ['name' => 'FISIATRIA'],
            ['name' => 'FISIOTERAPEUTA ESPORTIVO'],
            ['name' => 'FISIOTERAPEUTA GERAL'],
            ['name' => 'FONOAUDIÓLOGO'],
            ['name' => 'GASTROENTEROLOGIA'],
            ['name' => 'GASTROENTEROLOGISTA PEDRIATRA'],
            ['name' => 'GENETICISTA (MEDICO)'],
            ['name' => 'GERIATRA'],
            ['name' => 'GINECOLOGIA'],
            ['name' => 'GINECOLOGIA E OBSTETRICIA'],
            ['name' => 'HEMATOLOGIA'],
            ['name' => 'HEMOTERAPEUTA'],
            ['name' => 'HIPERBARISTA'],
            ['name' => 'HIPNÓLOGO'],
            ['name' => 'INFECTOLOGISTA'],
            ['name' => 'INSTRUMENTADOR CIRURGICO'],
            ['name' => 'INTENSIVISTA'],
            ['name' => 'LEGISTA'],
            ['name' => 'MASSAGISTA'],
            ['name' => 'MASTOLOGISTA'],
            ['name' => 'MEDICINA ESTÉTICA'],
            ['name' => 'MEDICINA NUCLEAR'],
            ['name' => 'MEDICO COLOPROCTOLOGISTA'],
            ['name' => 'MEDICO DE FAMILIA E COMUNIDADE'],
            ['name' => 'MEDICO DO TRABALHO'],
            ['name' => 'MEDICO EM MEDICINA DE TRÁFEGO'],
            ['name' => 'MEDICO EM MEDICINA PREVENTIVA E SOCIAL'],
            ['name' => 'MEDICO ESTRATEGIA SAUDE DA FAMILIA'],
            ['name' => 'MÉDICO GENERALISTA'],
            ['name' => 'MEDICO HOMEOPATA'],
            ['name' => 'MEDICO PATOLOGISTA CLINICO / MEDICINA LABORATORIAL'],
            ['name' => 'MEDICO RESIDENTE'],
            ['name' => 'MEDICO VETERINARIO'],
            ['name' => 'MUSICOTERAPEUTA'],
            ['name' => 'NEFROLOGIA'],
            ['name' => 'NEUROCIRURGIÃO'],
            ['name' => 'NEUROFISIOLOGIA CLINICA'],
            ['name' => 'NEUROLOGIA'],
            ['name' => 'NEUROPEDIATRIA'],
            ['name' => 'NEUROPSICÓLOGO'],
            ['name' => 'NUTRICIONISTA'],
            ['name' => 'NUTROLOGIA'],
            ['name' => 'ODONTOLOGISTA'],
            ['name' => 'ODONTOPEDIATRIA'],
            ['name' => 'OFTALMOLOGISTA'],
            ['name' => 'ONCOLOGIA '],
            ['name' => 'ORTODONTIA E ORTOPEDIA FACIAL'],
            ['name' => 'ORTOPEDIA E TRAUMATOLOGIA'],
            ['name' => 'ORTOPEDISTA'],
            ['name' => 'ORTOPTISTA '],
            ['name' => 'OSTEOPATIA'],
            ['name' => 'OTORRINOLARINGOLOGISTA'],
            ['name' => 'OUTRAS'],
            ['name' => 'PATOLOGISTA'],
            ['name' => 'PEDIATRIA'],
            ['name' => 'PNEUMOLOGISTA'],
            ['name' => 'PODOLOGIA'],
            ['name' => 'PRÉ-ATENDIMENTO **'],
            ['name' => 'PREPARADOR FÍSICO'],
            ['name' => 'PROCTOLOGISTA'],
            ['name' => 'PSICANALISTA'],
            ['name' => 'PSICOLOGIA CLINICA'],
            ['name' => 'PSICOPEDAGOGO'],
            ['name' => 'PSIQUIATRA'],
            ['name' => 'QUIROPRAXIA'],
            ['name' => 'RADIOLOGISTA / IMAGINOLOGISTA'],
            ['name' => 'RADIOTERAPEUTA'],
            ['name' => 'RESPONSÁVEL TÉCNICO **'],
            ['name' => 'REUMATOLOGIA'],
            ['name' => 'SANITARISTA'],
            ['name' => 'TÉCNICO DE ENFERMAGEM'],
            ['name' => 'TÉCNICO DE ENFERMAGEM DO TRABALHO'],
            ['name' => 'TÉCNICO DE LABORATÓRIO DE ANÁLISES FÍSICO-QUÍMICAS (MATERIAIS DE CONSTRUÇÃO)'],
            ['name' => 'TÉCNICO EM ACUPUNTURA'],
            ['name' => 'TÉCNICO EM FOTÔNICA'],
            ['name' => 'TÉCNICO EM HIGIENE DENTAL'],
            ['name' => 'TÉCNICO EM PATOLOGIA CLÍNICA'],
            ['name' => 'TÉCNICO EM RADIOLOGIA E IMAGENOLOGIA'],
            ['name' => 'TERAPEUTA'],
            ['name' => 'TERAPEUTA OCUPACIONAL'],
            ['name' => 'TRABALHADOR DE SERVIÇOS DE LIMPEZA E CONSERVAÇÃO DE ÁREAS PÚBLICAS'],
            ['name' => 'ULTRASSONOGRAFISTA'],
            ['name' => 'UROLOGIA'],
            ['name' => 'VISITADOR SANITÁRIO'],
    ];

        foreach($data as $d) {
            Especialidade::firstOrCreate([
                'name' => $d['name']
            ]);
        }
    }
}
